name: release

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: "recursive"

      - name: Install Dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y \
            libpixman-1-dev libfreetype6-dev libharfbuzz-dev zlib1g-dev \
            libx11-dev libxcursor-dev libxi-dev libxrandr-dev libgl1-mesa-dev \
            libfontconfig1-dev

      - name: Install Skia
        run: |
          this_dir="${{ github.workspace }}"
          skia_url=$(source $this_dir/laf/misc/skia-url.sh | xargs)
          skia_file=$(basename $skia_url)
          curl --ssl-revoke-best-effort -L -o "$skia_file" "$skia_url"
          unzip "$skia_file" -d skia

      - uses: aseprite/get-ninja@main

      - name: Generating Makefiles
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DENABLE_TESTS=OFF \
            -DENABLE_SCRIPTING=ON \
            -DLAF_BACKEND=skia \
            -DSKIA_DIR=$(realpath skia) \
            -DSKIA_LIBRARY_DIR=$(realpath skia/out/Release-x64)

      - name: Compiling
        run: cd build && ninja

      - name: Package
        run: |
          mkdir -p package
          cp -r build/bin/* package/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: aseprite-linux-x64
          path: package/
